spring:
  rabbitmq:
    host: localhost
    port: 5672  
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    connection-timeout: 10000
    requested-heartbeat: 10
    listener:
      simple:
        default-requeue-rejected: false

logging:
  level:
    root: INFO

app:
  rabbitmq:
    create-vdc-queue: VIRTUALCARD_REQUEST
    create-vdc-queue-retry: VIRTUALCARD_REQUEST_RETRY

    error-vdc-queue: VIRTUALCARD_VDC_ERROR
    error-vdc-queue-retry: VIRTUALCARD_VDC_ERROR_RETRY

    exchange: VIRTUALCARD_EXCHANGE

    retry: 2
    time-to-live: 10000