spring:
  rabbitmq:
    host: localhost
    port: 5672  
    username: guest
    password: guest
    listener:
      simple:
#        retry:
#          enabled: true
#          initial-interval: 3s
#          max-attempts: 5
#          max-interval: 10s
#          multiplier: 2
        default-requeue-rejected: false
         
server:
  port: 8081
app:
  rabbitmq:
    create-vdc-queue: VIRTUALCARD_CREATE_VDC
    create-vdc-queue-retry: VIRTUALCARD_CREATE_VDC_RETRY
    create-vdc-queue-error: VIRTUALCARD_CREATE_VDC_ERROR

    fee-charge-queue: VIRTUALCARD_FEE_CHARGE
    fee-charge-queue-retry: VIRTUALCARD_FEE_CHARGE_RETRY
    fee-charge-queue-error: VIRTUALCARD_FEE_CHARGE_ERROR
    
    exchange: VIRTUALCARD_EXCHANGE
    exchange_error: VIRTUALCARD_EXCHANGE_ERROR         